version: 2.1

master_branch_only: &master_branch_only
  filters:
    branches:
      only: /^main$/
    tags:
      ignore: /.*/

production_only: &production_only
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /.*/

composer_install: &composer_install
  name: Composer install
  command: ./composer.phar install -n

jobs:
  build:
    docker:
      - image: cinexpert/alpine-php-build:latest
        auth:
          username: ${DOCKER_HUB_LOGIN}
          password: ${DOCKER_HUB_PASSWORD}
    resource_class: large
    working_directory: /var/www/html
    steps:
      - checkout
      - run:
          <<: *composer_install
      - persist_to_workspace:
          root: /var/www/html
          paths:
            - .

  static:
    docker:
      - image: cinexpert/alpine-php-apache-build:latest
        auth:
          username: ${DOCKER_HUB_LOGIN}
          password: ${DOCKER_HUB_PASSWORD}
    working_directory: /var/www/html
    resource_class: large
    steps:
      - attach_workspace:
          at: /var/www/html
      - run:
          name: PHPStan
          command: |
            mkdir -p results/PHPStan
            php -d memory_limit=4G vendor/bin/phpstan --error-format=junit > results/PHPStan/result.xml; php -d memory_limit=4G vendor/bin/phpstan
      - run:
          name: PHPCS
          command: |
            mkdir -p results/PHPCS
            vendor/bin/phpcs module
      - store_test_results:
          path: results
      - store_artifacts:
          path: results

workflows:
  version: 2
  testing:
    jobs:
      - build
      - static:
          requires:
            - build
